export default {
  APPLY_AGENT_INFO: 'APPLY_AGENT_INFO',
  APPLY_BRANDING: 'APPLY_BRANDING',
  APPLY_CLIENT_DATA: 'APPLY_CLIENT_DATA',
  APPLY_FOOTER: 'APPLY_FOOTER',
  APPLY_HEADER: 'APPLY_HEADER',
  APPLY_NAVIGATION: 'APPLY_NAVIGATION',
  APPLY_WEBSITE_TITLE: 'APPLY_WEBSITE_TITLE',
  APPLY_WEBSITE_FAVICON: 'APPLY_WEBSITE_FAVICON',
  TOAST: 'TOAST',
  TOGGLE: 'TOGGLE'
};
